logger:
  line_length: 79
imageloader:
  label_mode: 'categorical'
  batch_size: 32
  image_size:
    - 256
    - 256
  seed: 20220610
  validation_split: 0.1
model:
  loss: categorical_crossentropy
  optimizer: Adadelta
  load_existing: False
  fit:
    epochs: 2
    verbose: 2
--- # optimizers
Adam:
Adadelta:
  learning_rate: 1.
  rho: 0.995
  epsilon: 1e-7